name: Deploy Lambda - daily

on:
  push:
    branches: [main]
    paths:
      - "lambda/daily/**"
      - ".github/workflows/deploy-daily.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FUNCTION_NAME: org-daily-boj-bot
      REGION: ap-northeast-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./lambda/daily
        run: npm install --omit=dev

      - name: Zip Lambda function
        working-directory: ./lambda/daily
        run: zip -r lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.REGION }}
          function_name: ${{ env.FUNCTION_NAME }}
          zip_file: lambda/daily/lambda.zip

      - name: Wait for Lambda update to finish
        run: sleep 10

      - name: Update Lambda environment variables
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FUNCTION_NAME: ${{ env.FUNCTION_NAME }}
          REGION: ${{ env.REGION }}
        run: |
          aws lambda update-function-configuration \
          --function-name $FUNCTION_NAME \
          --region $REGION \
          --environment "Variables={
            DISCORD_WEBHOOK='${{ secrets.DISCORD_WEBHOOK }}',
            GITHUB_API_URL='${{ secrets.GITHUBAPI_URL }}',
            ACCESS_TOKEN='${{ secrets.ACCESS_TOKEN }}',
            NOTION_TOKEN='${{ secrets.NOTION_TOKEN }}',
            NOTION_DATABASE_ID='${{ secrets.NOTION_DATABASE_ID }}',
            ASSIGNEES='${{ secrets.ASSIGNEES }}',
            IMP_RANDOM_QUERY='${{ secrets.IMP_RANDOM_QUERY }}',
            QUERY_FORMAT='${{ secrets.QUERY_FORMAT }}',
            PARTICIPANTS='${{ secrets.PARTICIPANTS }}'
          }"
